services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.16
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: ${MEILI_NO_ANALYTICS}
      MEILI_ENV: ${MEILI_ENV}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data

volumes:
  redis_data:
  meili_data:
